services:
  backend:
    build: .
    container_name: cosmetics_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/smart_cosmetics_crm
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data:ro
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: cosmetics_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: cosmetics_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cosmetics_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: