const EVENTS = {
  AUTH: {
    USER_REGISTERED: 'USER_REGISTERED',
    EMAIL_VERIFICATION_REQUESTED: 'EMAIL_VERIFICATION_REQUESTED',
    USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED'
  },
  CART: {
    CART_MERGED: 'CART_MERGED'
  },
  ORDER: {
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_CANCELLED: 'ORDER_CANCELLED'
  },
  PAYMENT: {
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILED: 'PAYMENT_FAILED'
  },
  PRODUCT: {
    PRODUCT_CREATED: 'PRODUCT_CREATED',
    PRODUCT_UPDATED: 'PRODUCT_UPDATED',
    PRODUCT_DELETED: 'PRODUCT_DELETED'
  }
};

module.exports = EVENTS;
