const PAYMENT_METHODS = {
  COD: 'COD',
  PAYOS: 'PAYOS'
};

const PAYMENT_STATUSES = {
  UNPAID: 'UNPAID',
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

const ORDER_STATUSES = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

module.exports = {
  PAYMENT_METHODS,
  PAYMENT_METHOD_VALUES: Object.values(PAYMENT_METHODS),
  PAYMENT_STATUSES,
  PAYMENT_STATUS_VALUES: Object.values(PAYMENT_STATUSES),
  ORDER_STATUSES,
  ORDER_STATUS_VALUES: Object.values(ORDER_STATUSES)
};
